{{- range .Values.gateways -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  gatewayClassName: ngf
  infrastructure:
    parametersRef:
      group: gateway.nginx.org
      kind: NginxProxy
      name: {{ .name }}-proxy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    {{- if and .https .https.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .https.hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .https.tlsSecretName }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
---
{{ end -}}
