{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway-fabric
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    release: {{ .Values.serviceMonitor.prometheusReleaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{- end }}
